/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/arbitrage/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Arbitrage
         * @description Lista oportunidades de arbitraje.
         */
        get: operations["list_arbitrage_api_v1_arbitrage__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arbitrage/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Arbitrage History
         * @description Historial completo de arbitrajes (todos los estados por defecto).
         *     Incluye `closed_at` y `sport` para visualización.
         */
        get: operations["arbitrage_history_api_v1_arbitrage_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arbitrage/{arb_id}/revalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Revalidate Arbitrage
         * @description Re-evalúa el arb contra las cuotas más recientes en DB. Devuelve si sigue
         *     siendo ejecutable (alive), requiere confirmación por haber caído de valor
         *     (stale), o ya no existe (dead). No modifica estado.
         */
        get: operations["revalidate_arbitrage_api_v1_arbitrage__arb_id__revalidate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sports */
        get: operations["list_sports_api_v1_sports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sports/{sport_key}/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leagues */
        get: operations["list_leagues_api_v1_sports__sport_key__leagues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_api_v1_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Match */
        get: operations["get_match_api_v1_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/odds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match Odds
         * @description Obtiene las últimas cuotas de todos los bookmakers para un partido.
         */
        get: operations["get_match_odds_api_v1_matches__match_id__odds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunities */
        get: operations["list_opportunities_api_v1_opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Opportunities History
         * @description Historial completo de value bets (todos los estados por defecto).
         *     Sin auth, mismo patrón que /arbitrage/history. Incluye sport/league
         *     para colorear en la UI.
         */
        get: operations["opportunities_history_api_v1_opportunities_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opportunity */
        get: operations["get_opportunity_api_v1_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/take": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take Opportunity */
        post: operations["take_opportunity_api_v1_opportunities__opportunity_id__take_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/paper/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Paper Bets */
        get: operations["list_paper_bets_api_v1_paper_bets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/paper/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paper Stats
         * @description Métricas agregadas del paper trading. `source_type` filtra a un origen.
         */
        get: operations["paper_stats_api_v1_paper_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/paper/clv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paper Clv
         * @description Closing Line Value: cuánto batiste a la línea de cierre en promedio.
         *
         *     CLV positivo = tomaste cuotas mejores que el cierre → señal de skill.
         *     Mejor predictor del edge real que el ROI a corto plazo (varianza dominante).
         */
        get: operations["paper_clv_api_v1_paper_clv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_users_config_get"];
        /** Update Config */
        put: operations["update_config_api_v1_users_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/bankroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bankrolls */
        get: operations["list_bankrolls_api_v1_users_bankroll_get"];
        put?: never;
        /** Create Bankroll */
        post: operations["create_bankroll_api_v1_users_bankroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/bankroll/{bankroll_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Bankroll */
        put: operations["update_bankroll_api_v1_users_bankroll__bankroll_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_v1_performance_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts_config_get"];
        put?: never;
        /** Create Alert */
        post: operations["create_alert_api_v1_alerts_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/config/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Alert */
        put: operations["update_alert_api_v1_alerts_config__alert_id__put"];
        post?: never;
        /** Delete Alert */
        delete: operations["delete_alert_api_v1_alerts_config__alert_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/config/{alert_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Alert
         * @description Dispara un envío de prueba al canal configurado en este alert. Útil para
         *     validar credenciales (token Telegram, SMTP, URL webhook) sin esperar a
         *     que aparezca una oportunidad real.
         *
         *     No persiste nada — el resultado se devuelve inline. Errores del canal
         *     (timeout, auth) se devuelven como `{ok: false, error: "..."}` para que
         *     la UI los muestre, no como 5xx.
         */
        post: operations["test_alert_api_v1_alerts_config__alert_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Stats
         * @description Estadísticas generales del sistema.
         */
        get: operations["system_stats_api_v1_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/trigger/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Fetch
         * @description Trigger manual del job de fetch de cuotas.
         */
        post: operations["trigger_fetch_api_v1_admin_trigger_fetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/trigger/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Detect
         * @description Trigger manual del job de detección.
         */
        post: operations["trigger_detect_api_v1_admin_trigger_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Seed
         * @description Trigger manual del seed de datos.
         */
        post: operations["trigger_seed_api_v1_admin_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Leagues
         * @description Lista todas las ligas con su estado de detection_enabled y active.
         */
        get: operations["list_leagues_api_v1_admin_leagues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/leagues/{league_key}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle League Detection
         * @description Activa o desactiva la detección (y por cascada, el fetch) de una liga.
         *     Toggle persistente: el seed no lo sobrescribe en redeploys posteriores.
         */
        post: operations["toggle_league_detection_api_v1_admin_leagues__league_key__toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arbitrage/{arbitrage_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Arbitrage */
        post: operations["execute_arbitrage_api_v1_arbitrage__arbitrage_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arbitrage/{arbitrage_id}/exposure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Arbitrage Exposure
         * @description Exposición actual del usuario sobre este arb: P&L por escenario de outcome,
         *     detección de partial fill, sugerencias de rebalanceo por leg rejected.
         */
        get: operations["get_arbitrage_exposure_api_v1_arbitrage__arbitrage_id__exposure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bets */
        get: operations["list_bets_api_v1_bets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bets/{bet_id}/place": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Place Bet */
        patch: operations["place_bet_api_v1_bets__bet_id__place_patch"];
        trace?: never;
    };
    "/api/v1/bets/{bet_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reject Bet */
        patch: operations["reject_bet_api_v1_bets__bet_id__reject_patch"];
        trace?: never;
    };
    "/api/v1/bets/{bet_id}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Settle Bet */
        patch: operations["settle_bet_api_v1_bets__bet_id__settle_patch"];
        trace?: never;
    };
    "/api/v1/planning/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Daily Plan
         * @description Retorna un plan priorizado: qué arbs ejecutar y con qué stake para cubrir
         *     el target diario sin exceder el cap.
         */
        get: operations["get_daily_plan_api_v1_planning_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertConfigCreate */
        AlertConfigCreate: {
            /** Channel */
            channel: string;
            /** Destination */
            destination: string;
            /**
             * Min Value Pct
             * @default 0.05
             */
            min_value_pct: number;
            /**
             * Sports Filter
             * @default []
             */
            sports_filter: string[];
            /**
             * Leagues Filter
             * @default []
             */
            leagues_filter: string[];
        };
        /** AlertConfigResponse */
        AlertConfigResponse: {
            /** Id */
            id: number;
            /** Channel */
            channel: string;
            /** Destination */
            destination: string;
            /** Min Value Pct */
            min_value_pct: number;
            /** Sports Filter */
            sports_filter: string[] | null;
            /** Leagues Filter */
            leagues_filter: string[] | null;
            /** Active */
            active: boolean;
        };
        /** AlertConfigUpdate */
        AlertConfigUpdate: {
            /** Destination */
            destination?: string | null;
            /** Min Value Pct */
            min_value_pct?: number | null;
            /** Sports Filter */
            sports_filter?: string[] | null;
            /** Leagues Filter */
            leagues_filter?: string[] | null;
            /** Active */
            active?: boolean | null;
        };
        /**
         * AlertTestResponse
         * @description Resultado de un envío de prueba al canal configurado.
         */
        AlertTestResponse: {
            /** Ok */
            ok: boolean;
            /** Error */
            error?: string | null;
        };
        /** AllocationSuggestionResponse */
        AllocationSuggestionResponse: {
            /** Arbitrage Id */
            arbitrage_id: number;
            /** Match Label */
            match_label: string;
            /** Market Type */
            market_type: string;
            /** Profit Pct */
            profit_pct: number;
            /** Suggested Stake */
            suggested_stake: number;
            /** Expected Profit */
            expected_profit: number;
            /** Bookmakers */
            bookmakers: string[];
        };
        /** ArbHistoryItem */
        ArbHistoryItem: {
            /** Id */
            id: number;
            /** Match */
            match: string;
            /** Sport */
            sport: string;
            /** League */
            league: string;
            /** Commence Time */
            commence_time: string;
            /** Market Type */
            market_type: string;
            /** Profit Pct */
            profit_pct: number;
            /** Total Implied */
            total_implied: number;
            /** Num Legs */
            num_legs: number;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "expired" | "dead";
            /** Detected At */
            detected_at: string;
            /** Closed At */
            closed_at: string | null;
        };
        /**
         * ArbLegResponse
         * @description Forma exacta de cada leg almacenada en `arb.legs` (JSON column).
         */
        ArbLegResponse: {
            /** Outcome */
            outcome: string;
            /** Outcome Name */
            outcome_name: string;
            /** Bookmaker */
            bookmaker: string;
            /** Odds */
            odds: number;
            /** Stake Pct */
            stake_pct: number;
        };
        /** ArbResponse */
        ArbResponse: {
            /** Id */
            id: number;
            /** Match */
            match: string;
            /** Sport */
            sport: string;
            /** League */
            league: string;
            /** Commence Time */
            commence_time: string;
            /** Market Type */
            market_type: string;
            /** Profit Pct */
            profit_pct: number;
            /** Total Implied */
            total_implied: number;
            /** Legs */
            legs: components["schemas"]["ArbLegResponse"][];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "expired" | "dead";
            /** Detected At */
            detected_at: string;
        };
        /** BankrollCreate */
        BankrollCreate: {
            /**
             * Name
             * @default Principal
             */
            name: string;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /** Initial Amount */
            initial_amount: number;
        };
        /** BankrollResponse */
        BankrollResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Initial Amount */
            initial_amount: number;
            /** Current Amount */
            current_amount: number;
            /**
             * Reserved Amount
             * @default 0
             */
            reserved_amount: number;
            /**
             * Available Amount
             * @default 0
             */
            available_amount: number;
        };
        /** BankrollUpdate */
        BankrollUpdate: {
            /** Name */
            name?: string | null;
            /** Current Amount */
            current_amount?: number | null;
        };
        /** BetResponse */
        BetResponse: {
            /** Id */
            id: number;
            /** Arbitrage Id */
            arbitrage_id: number | null;
            /** Opportunity Id */
            opportunity_id: number | null;
            /** Bookmaker Id */
            bookmaker_id: number;
            /** Outcome Id */
            outcome_id: number;
            /** Stake Amount */
            stake_amount: number;
            /** Odds At Detection */
            odds_at_detection: number | null;
            /** Odds At Placement */
            odds_at_placement: number | null;
            /** Commission Pct */
            commission_pct: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "placed" | "confirmed" | "rejected" | "void" | "settled";
            /** Result */
            result: ("won" | "lost" | "void" | "half_won" | "half_lost") | null;
            /** Actual Payout */
            actual_payout: number | null;
            /** Profit Loss */
            profit_loss: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Placed At */
            placed_at: string | null;
            /** Settled At */
            settled_at: string | null;
        };
        /** CLVBreakdown */
        CLVBreakdown: {
            /** Bets */
            bets: number;
            /** Avg Clv Pct */
            avg_clv_pct: number;
            /** Avg Log Clv */
            avg_log_clv: number;
        };
        /** CLVResponse */
        CLVResponse: {
            /** Total Bets */
            total_bets: number;
            /** Bets With Clv */
            bets_with_clv: number;
            /** Coverage Pct */
            coverage_pct: number;
            /** Avg Clv Pct */
            avg_clv_pct: number | null;
            /** Median Clv Pct */
            median_clv_pct: number | null;
            /** Avg Log Clv */
            avg_log_clv: number | null;
            /** Positive Count */
            positive_count: number;
            /** Zero Count */
            zero_count: number;
            /** Negative Count */
            negative_count: number;
            /** By Source */
            by_source: {
                [key: string]: components["schemas"]["CLVBreakdown"];
            };
            /** By Bookmaker */
            by_bookmaker: {
                [key: string]: components["schemas"]["CLVBreakdown"];
            };
        };
        /** DailyPlanResponse */
        DailyPlanResponse: {
            /** Currency */
            currency: string;
            /** Daily Investment Cap */
            daily_investment_cap: number;
            /** Target Pct */
            target_pct: number;
            /** Target Profit */
            target_profit: number;
            /** Max Stake Per Arb Pct */
            max_stake_per_arb_pct: number;
            /** Available Arbs */
            available_arbs: number;
            /** Allocations */
            allocations: components["schemas"]["AllocationSuggestionResponse"][];
            /** Total Suggested Stake */
            total_suggested_stake: number;
            /** Expected Total Profit */
            expected_total_profit: number;
            /** Target Coverage Pct */
            target_coverage_pct: number;
            /** Status */
            status: string;
            /** Recommendation */
            recommendation: string;
            /**
             * Exposure By Bookmaker
             * @default {}
             */
            exposure_by_bookmaker: {
                [key: string]: number;
            };
            /**
             * Concentration Warnings
             * @default []
             */
            concentration_warnings: string[];
        };
        /** ExecuteArbitrageRequest */
        ExecuteArbitrageRequest: {
            /** Bankroll Id */
            bankroll_id: number;
            /** Total Stake */
            total_stake: number;
            /**
             * Force If Stale
             * @default false
             */
            force_if_stale: boolean;
        };
        /** ExecutionPlanResponse */
        ExecutionPlanResponse: {
            /** Arbitrage Id */
            arbitrage_id: number;
            /** Match Label */
            match_label: string;
            /** Market Type */
            market_type: string;
            /** Total Stake */
            total_stake: number;
            /** Currency */
            currency: string;
            /** Expected Profit */
            expected_profit: number;
            /** Profit Pct */
            profit_pct: number;
            /** Legs */
            legs: components["schemas"]["LegInstructionResponse"][];
        };
        /** ExposureResponse */
        ExposureResponse: {
            /** Arbitrage Id */
            arbitrage_id: number;
            /** Currency */
            currency: string;
            /** Is Partial Fill */
            is_partial_fill: boolean;
            /** Any Rejected */
            any_rejected: boolean;
            /** All Placed */
            all_placed: boolean;
            /** Total Placed Stake */
            total_placed_stake: number;
            /** Worst Case Pnl */
            worst_case_pnl: number;
            /** Best Case Pnl */
            best_case_pnl: number;
            /** Scenarios */
            scenarios: components["schemas"]["OutcomeScenarioResponse"][];
            /** Legs */
            legs: components["schemas"]["LegSummaryResponse"][];
            /** Replacement Suggestions */
            replacement_suggestions: components["schemas"]["ReplacementSuggestionResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeagueToggleRequest */
        LeagueToggleRequest: {
            /** Detection Enabled */
            detection_enabled: boolean;
        };
        /** LegInstructionResponse */
        LegInstructionResponse: {
            /** Bet Id */
            bet_id: number;
            /** Bookmaker Key */
            bookmaker_key: string;
            /** Bookmaker Name */
            bookmaker_name: string;
            /** Outcome Key */
            outcome_key: string;
            /** Outcome Name */
            outcome_name: string;
            /** Stake Amount */
            stake_amount: number;
            /** Target Odds */
            target_odds: number;
            /** Min Acceptable Odds */
            min_acceptable_odds: number;
            /** Commission Pct */
            commission_pct: number;
        };
        /** LegSummaryResponse */
        LegSummaryResponse: {
            /** Bet Id */
            bet_id: number;
            /** Outcome Key */
            outcome_key: string;
            /** Outcome Name */
            outcome_name: string;
            /** Bookmaker Key */
            bookmaker_key: string;
            /** Bookmaker Name */
            bookmaker_name: string;
            /** Stake Amount */
            stake_amount: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "placed" | "confirmed" | "rejected" | "void" | "settled";
            /** Odds Effective */
            odds_effective: number | null;
            /** Commission Pct */
            commission_pct: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MarketResponse */
        MarketResponse: {
            /** Id */
            id: number;
            /** Market Type Key */
            market_type_key: string;
            /** Market Type Name */
            market_type_name: string;
            /** Parameter */
            parameter: number | null;
            /**
             * Outcomes
             * @default []
             */
            outcomes: components["schemas"]["OutcomeResponse"][];
        };
        /** MatchDetailResponse */
        MatchDetailResponse: {
            /** Id */
            id: number;
            /** External Id */
            external_id: string | null;
            /**
             * Commence Time
             * Format: date-time
             */
            commence_time: string;
            /** Status */
            status: string;
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            home_team: components["schemas"]["TeamBrief"];
            away_team: components["schemas"]["TeamBrief"];
            /** Season Id */
            season_id: number;
            /**
             * Markets
             * @default []
             */
            markets: components["schemas"]["MarketResponse"][];
        };
        /** MatchResponse */
        MatchResponse: {
            /** Id */
            id: number;
            /** External Id */
            external_id: string | null;
            /**
             * Commence Time
             * Format: date-time
             */
            commence_time: string;
            /** Status */
            status: string;
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            home_team: components["schemas"]["TeamBrief"];
            away_team: components["schemas"]["TeamBrief"];
        };
        /** OddsResponse */
        OddsResponse: {
            /** Outcome Id */
            outcome_id: number;
            /** Outcome Key */
            outcome_key: string;
            /** Outcome Name */
            outcome_name: string;
            /** Bookmaker Key */
            bookmaker_key: string;
            /** Bookmaker Name */
            bookmaker_name: string;
            /** Price */
            price: number;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
        };
        /** OpportunityDetailResponse */
        OpportunityDetailResponse: {
            /** Id */
            id: number;
            /** Match Home Team */
            match_home_team: string;
            /** Match Away Team */
            match_away_team: string;
            /**
             * Commence Time
             * Format: date-time
             */
            commence_time: string;
            /** Market Type */
            market_type: string;
            /** Outcome Name */
            outcome_name: string;
            /** Bookmaker Name */
            bookmaker_name: string;
            /** Odds Price */
            odds_price: number;
            /** Consensus Prob */
            consensus_prob: number;
            /** Implied Prob */
            implied_prob: number;
            /** Value Pct */
            value_pct: number;
            /** Kelly Stake Pct */
            kelly_stake_pct: number | null;
            /**
             * Is Steam
             * @default false
             */
            is_steam: boolean;
            /** Status */
            status: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Recommended Stake */
            recommended_stake?: number | null;
            /** Staking Method */
            staking_method?: string | null;
            /** Bankroll Used */
            bankroll_used?: number | null;
        };
        /** OpportunityHistoryItem */
        OpportunityHistoryItem: {
            /** Id */
            id: number;
            /** Match */
            match: string;
            /** Sport */
            sport: string;
            /** League */
            league: string;
            /** Commence Time */
            commence_time: string;
            /** Market Type */
            market_type: string;
            /** Outcome Name */
            outcome_name: string;
            /** Bookmaker */
            bookmaker: string;
            /** Odds Price */
            odds_price: number;
            /** Value Pct */
            value_pct: number;
            /** Kelly Stake Pct */
            kelly_stake_pct: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "expired";
            /** Detected At */
            detected_at: string;
            /** Closed At */
            closed_at: string | null;
        };
        /** OpportunityResponse */
        OpportunityResponse: {
            /** Id */
            id: number;
            /** Match Home Team */
            match_home_team: string;
            /** Match Away Team */
            match_away_team: string;
            /**
             * Commence Time
             * Format: date-time
             */
            commence_time: string;
            /** Market Type */
            market_type: string;
            /** Outcome Name */
            outcome_name: string;
            /** Bookmaker Name */
            bookmaker_name: string;
            /** Odds Price */
            odds_price: number;
            /** Consensus Prob */
            consensus_prob: number;
            /** Implied Prob */
            implied_prob: number;
            /** Value Pct */
            value_pct: number;
            /** Kelly Stake Pct */
            kelly_stake_pct: number | null;
            /**
             * Is Steam
             * @default false
             */
            is_steam: boolean;
            /** Status */
            status: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
        };
        /** OutcomeResponse */
        OutcomeResponse: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /** OutcomeScenarioResponse */
        OutcomeScenarioResponse: {
            /** Outcome Key */
            outcome_key: string;
            /** Outcome Name */
            outcome_name: string;
            /** Pnl */
            pnl: number;
            /** Covered */
            covered: boolean;
        };
        /** PaperBetResponse */
        PaperBetResponse: {
            /** Id */
            id: number;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "value" | "arbitrage";
            /** Match */
            match: string;
            /** Outcome */
            outcome: string;
            /** Bookmaker */
            bookmaker: string;
            /** Odds Taken */
            odds_taken: number;
            /** Stake Units */
            stake_units: number;
            /** Ev At Placement */
            ev_at_placement: number | null;
            /** Placed At */
            placed_at: string;
            /**
             * Result
             * @enum {string}
             */
            result: "pending" | "won" | "lost" | "void";
            /** Profit Units */
            profit_units: number | null;
        };
        /** PerformanceSummary */
        PerformanceSummary: {
            /** Total Bets */
            total_bets: number;
            /** Won */
            won: number;
            /** Lost */
            lost: number;
            /** Pending */
            pending: number;
            /** Win Rate */
            win_rate: number;
            /** Total Staked */
            total_staked: number;
            /** Total Profit */
            total_profit: number;
            /** Roi */
            roi: number;
        };
        /** PlaceBetRequest */
        PlaceBetRequest: {
            /** Odds At Placement */
            odds_at_placement: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** RejectBetRequest */
        RejectBetRequest: {
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** ReplacementOptionResponse */
        ReplacementOptionResponse: {
            /** Bookmaker Key */
            bookmaker_key: string;
            /** Bookmaker Name */
            bookmaker_name: string;
            /** Odds */
            odds: number;
            /** Commission Pct */
            commission_pct: number;
        };
        /** ReplacementSuggestionResponse */
        ReplacementSuggestionResponse: {
            /** Outcome Key */
            outcome_key: string;
            /** Outcome Name */
            outcome_name: string;
            /** Rejected Bookmaker Key */
            rejected_bookmaker_key: string;
            /** Alternatives */
            alternatives: components["schemas"]["ReplacementOptionResponse"][];
        };
        /** RevalidationResponse */
        RevalidationResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "alive" | "stale" | "dead";
            /** Detected Profit Pct */
            detected_profit_pct: number;
            /** Current Profit Pct */
            current_profit_pct: number;
            /** Age Seconds */
            age_seconds: number;
            /** Current Legs */
            current_legs?: components["schemas"]["ArbLegResponse"][] | null;
        };
        /** SettleBetRequest */
        SettleBetRequest: {
            /**
             * Result
             * @enum {string}
             */
            result: "won" | "lost" | "void" | "half_won" | "half_lost";
            /** Actual Payout */
            actual_payout: number;
        };
        /** SportResponse */
        SportResponse: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Active */
            active: boolean;
        };
        /**
         * StatsBreakdown
         * @description Agregado por bucket (source o bookmaker) en `/paper/stats`.
         */
        StatsBreakdown: {
            /** Bets */
            bets: number;
            /** Profit Units */
            profit_units: number;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Total Bets */
            total_bets: number;
            /** Pending */
            pending: number;
            /** Won */
            won: number;
            /** Lost */
            lost: number;
            /** Void */
            void: number;
            /** Total Staked Units */
            total_staked_units: number;
            /** Total Profit Units */
            total_profit_units: number;
            /** Roi Pct */
            roi_pct: number | null;
            /** Win Rate Pct */
            win_rate_pct: number | null;
            /** By Source */
            by_source: {
                [key: string]: components["schemas"]["StatsBreakdown"];
            };
            /** By Bookmaker */
            by_bookmaker: {
                [key: string]: components["schemas"]["StatsBreakdown"];
            };
        };
        /** TakeOpportunityRequest */
        TakeOpportunityRequest: {
            /** Bankroll Id */
            bankroll_id: number;
            /** Staking Method */
            staking_method?: string | null;
        };
        /** TakeOpportunityResponse */
        TakeOpportunityResponse: {
            /** Bet Id */
            bet_id: number;
            /** Stake Amount */
            stake_amount: number;
            /** Odds At Placement */
            odds_at_placement: number;
            /** Staking Method */
            staking_method: string;
        };
        /** TeamBrief */
        TeamBrief: {
            /** Id */
            id: number;
            /** Canonical Name */
            canonical_name: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** UserConfigResponse */
        UserConfigResponse: {
            /** Default Staking */
            default_staking: string;
            /** Kelly Fraction */
            kelly_fraction: number;
            /** Flat Stake Pct */
            flat_stake_pct: number;
            /** Min Value Threshold */
            min_value_threshold: number;
            /** Max Stake Pct */
            max_stake_pct: number;
            /** Preferred Sports */
            preferred_sports: string[] | null;
            /** Preferred Leagues */
            preferred_leagues: string[] | null;
            /** Risk Tolerance */
            risk_tolerance: string;
            /**
             * Default Currency
             * @default USD
             */
            default_currency: string;
            /**
             * Default Daily Target Pct
             * @default 1
             */
            default_daily_target_pct: number;
            /**
             * Default Max Stake Per Arb Pct
             * @default 15
             */
            default_max_stake_per_arb_pct: number;
        };
        /** UserConfigUpdate */
        UserConfigUpdate: {
            /** Default Staking */
            default_staking?: string | null;
            /** Kelly Fraction */
            kelly_fraction?: number | null;
            /** Flat Stake Pct */
            flat_stake_pct?: number | null;
            /** Min Value Threshold */
            min_value_threshold?: number | null;
            /** Max Stake Pct */
            max_stake_pct?: number | null;
            /** Preferred Sports */
            preferred_sports?: string[] | null;
            /** Preferred Leagues */
            preferred_leagues?: string[] | null;
            /** Risk Tolerance */
            risk_tolerance?: string | null;
            /** Default Currency */
            default_currency?: string | null;
            /** Default Daily Target Pct */
            default_daily_target_pct?: number | null;
            /** Default Max Stake Per Arb Pct */
            default_max_stake_per_arb_pct?: number | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Username */
            username: string;
            /**
             * Role
             * @enum {string}
             */
            role: "free" | "premium" | "admin";
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** LeagueResponse */
        app__api__v1__admin__LeagueResponse: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Country */
            country: string | null;
            /** Detection Enabled */
            detection_enabled: boolean;
            /** Active */
            active: boolean;
        };
        /** LeagueResponse */
        app__schemas__sport__LeagueResponse: {
            /** Id */
            id: number;
            /** Sport Id */
            sport_id: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Country */
            country: string | null;
            /** Active */
            active: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_arbitrage_api_v1_arbitrage__get: {
        parameters: {
            query?: {
                status?: string;
                min_profit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArbResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arbitrage_history_api_v1_arbitrage_history_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArbHistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revalidate_arbitrage_api_v1_arbitrage__arb_id__revalidate_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arb_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevalidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_sports_api_v1_sports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SportResponse"][];
                };
            };
        };
    };
    list_leagues_api_v1_sports__sport_key__leagues_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__sport__LeagueResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_api_v1_matches_get: {
        parameters: {
            query?: {
                sport?: string | null;
                league?: string | null;
                status?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_api_v1_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_odds_api_v1_matches__match_id__odds_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OddsResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunities_api_v1_opportunities_get: {
        parameters: {
            query?: {
                min_value?: number | null;
                market_type?: string | null;
                bookmaker?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opportunities_history_api_v1_opportunities_history_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityHistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunity_api_v1_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_opportunity_api_v1_opportunities__opportunity_id__take_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TakeOpportunityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TakeOpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_paper_bets_api_v1_paper_bets_get: {
        parameters: {
            query?: {
                result?: string | null;
                source_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperBetResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_stats_api_v1_paper_stats_get: {
        parameters: {
            query?: {
                source_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_clv_api_v1_paper_clv_get: {
        parameters: {
            query?: {
                source_type?: string | null;
                bookmaker_key?: string | null;
                result?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CLVResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_v1_users_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserConfigResponse"];
                };
            };
        };
    };
    update_config_api_v1_users_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bankrolls_api_v1_users_bankroll_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankrollResponse"][];
                };
            };
        };
    };
    create_bankroll_api_v1_users_bankroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankrollCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankrollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_bankroll_api_v1_users_bankroll__bankroll_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bankroll_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankrollUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankrollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_performance_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceSummary"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertConfigResponse"][];
                };
            };
        };
    };
    create_alert_api_v1_alerts_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertConfigCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_api_v1_alerts_config__alert_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alert_api_v1_alerts_config__alert_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_alert_api_v1_alerts_config__alert_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_stats_api_v1_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_fetch_api_v1_admin_trigger_fetch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_detect_api_v1_admin_trigger_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_seed_api_v1_admin_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_leagues_api_v1_admin_leagues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__api__v1__admin__LeagueResponse"][];
                };
            };
        };
    };
    toggle_league_detection_api_v1_admin_leagues__league_key__toggle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeagueToggleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__api__v1__admin__LeagueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_arbitrage_api_v1_arbitrage__arbitrage_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arbitrage_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteArbitrageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_arbitrage_exposure_api_v1_arbitrage__arbitrage_id__exposure_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arbitrage_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExposureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bets_api_v1_bets_get: {
        parameters: {
            query?: {
                status_filter?: string | null;
                arbitrage_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_bet_api_v1_bets__bet_id__place_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bet_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceBetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_bet_api_v1_bets__bet_id__reject_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bet_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settle_bet_api_v1_bets__bet_id__settle_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bet_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettleBetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_plan_api_v1_planning_daily_get: {
        parameters: {
            query: {
                /** @description ID del bankroll a usar */
                bankroll_id: number;
                /** @description Tope de inversión para hoy. Si no se pasa, usa bankroll.available_amount como default. */
                daily_cap?: number | null;
                /** @description Target de profit diario como %. Si no se pasa, usa user_config.default_daily_target_pct (default 1.0). */
                target_pct?: number | null;
                /** @description Tope de stake por arb como % del daily_cap. Si no, usa user_config.default_max_stake_per_arb_pct (default 15.0). */
                max_stake_per_arb_pct?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
